### ISSUE TITLE
Question: would you consider a BSD-licence?

### ISSUE THREAD

**Issue by niedakh** [gagolews/genieclust#1]
Hi,

this is a very nice package for performing hierarchical clustering. I see that you have licenced is as GPL. At the moment a large part of the python ML community (see the scikit-* family) releases BSD-licenced libraries to allow commercial usage of code, which helps build a business ecosystem around a library. Would you consider licencing your library as BSD?

**Comment by gagolews** [comment]
Yup, can do.
