### ISSUE TITLE
Please consider avoiding using deprecated MLpack version

### ISSUE THREAD

**Issue by nileshpatra** [gagolews/genieclust#72]
Hi,

As is visible in the repository of [RcppMLPACK](https://github.com/rcppmlpack/RcppMLPACK1/tree/master/src/mlpack), it embeds a copy of mlpack 1.0.10, which is ancient.

This is causing troubles and increasing maintenance issues, while updating the corresponding r-cran-genieclust package in Debian. Please consider to migrate to a R package which might provide bindings for an updated MLpack version, or any other alternative that is well maintained.

**Comment by gagolews** [comment]
sure

**Comment by gagolews** [comment]
Note to self: replace with:
https://cran.r-project.org/web/packages/mlpack/index.html
https://www.mlpack.org/doc/mlpack-3.4.2/doxygen/r_quickstart.html
