### ISSUE TITLE
nmslib dependency

### ISSUE THREAD

**Issue by MichaelRFox** [gagolews/genieclust#75]
nmslib, as of v2.1.1, cannot be installed under Windows using python v3.9+ (see issue #464 https://github.com/nmslib/nmslib/issues/464), causing pip install of genieclust to fail. It's been some time since this issue was identified (Dec 2020...almost 2 years ago) and the maintainer has yet to rectify it.  You may want to reconsider this dependency to keep your excellent code relevant.

**Comment by gagolews** [comment]
Thanks, fixed. A new release is now available on PyPI.

**Comment by MichaelRFox** [comment]
Thank you...installs correctly now on Python 10 😹

**Comment by gagolews** [comment]
Thanks for verifying this!
