### ISSUE TITLE
cluster_validity submodule in python missing

### ISSUE THREAD

**Issue by lm-jkominek** [gagolews/genieclust#82]
Hi, I've been using _genieclust_ for some of my work recently, and absolutely love the efficiency of it  - 10K rows and 10K columns, clustered in ~20 seconds, works fantastic. I wanted to try assessing the best number of clusters in my data, and the docs mention all the different indices to do that (Calinski-harabasz, Silhouette etc), but for some reason I cannot run/see their respective functions in my Python install. In fact, it looks like the entire _cluster_validity_ submodule is missing/hidden on my machine. 

```
>>> import genieclust as gc
>>> dir(gc)
['GIc', 'Genie', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'compare_partitions', 'genie', 'inequity', 'internal', 'plots', 'tools']
```

I use Python 3.11.4, and tried _genieclust_ v1.1.3, v1.1.4 as well as a direct github install of the latest dev version (v1.1.4.9001), with the same result. Any help or at least clarity on why that would be happening? Thanks a lot in advance!

**Comment by gagolews** [comment]
Ooops! I missed an import line in `__init__.py`! This is now corrected in the github version 

If you want to stick with the PyPI version (I plan a new PyPI release in 1-2 months), `import genieclust.cluster_validity` will do, for now.

Thanks for the report!

**Comment by lm-jkominek** [comment]
Thanks a lot, appreciate the rapid response! I don't mind using the Github version for now, will just update to v1.1.5 when it's out.
