### ISSUE TITLE
ValueError: incorrect n_clusters

### ISSUE THREAD

**Issue by chrico-bu-uab** [gagolews/genieclust#85]
What is the source of this error? I could not find it in any source code.

Thanks!

**Comment by chrico-bu-uab** [comment]
I think I figured it out - this error appears to be the result of selecting a value of n_clusters that exceeds the number of points to cluster.

**Comment by gagolews** [comment]
Yes, one of the conditions in internal.pyx is:

```
if not 0 <= n_clusters <= n:
        raise ValueError("incorrect n_clusters")
```
