### ISSUE TITLE
Update distance_ documentation? (I'm happy to make a pull request)

### ISSUE THREAD

**Issue by mrucker** [gagolews/genieclust#87]
First of all let me say I've been very impressed with Genie. I've tried it on several benchmark datasets with simulated noise. Genie is consistently one of the best performing clustering algorithms.

Now, a question. It looks like Genie is applying `cummin` to `distances_` by default. The current documentation makes it sound like `cummin` isn't applied by default. Should the documentation be updated? I'm happy to send you a pull request with the change with the change.

**Comment by gagolews** [comment]
Sorry for a late response!

Yes, it'd be nice if you filed a pull request; the relevant files are: genieclust/genie.py and R/gclust.R.

Thank you!

**Comment by gagolews** [comment]
Thanks for the update!
